siteblog/blog/urls.py
from django.urls import path

from .views import IndexView
from .views import PostDetailView
from .views import PostByCategory
from .views import PostByTag
from .views import Search

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category/<slug:slug>/', PostByCategory.as_view(), name='category'),
    path('tag/<slug:slug>/', PostByTag.as_view(), name='tag'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post'),
    path('search/', Search.as_view(), name='search')
]

siteblog/siteblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteblog/blog/models.py
from django.db import models
from django.urls import reverse, reverse_lazy


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='URL')

    def get_absolute_url(self):
        return reverse('blog:category', args=[str(self.slug)])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['title']


class Tag(models.Model):
    title = models.CharField(max_length=50, verbose_name='Наименование')
    slug = models.SlugField(max_length=50, unique=True, verbose_name='URL')

    def get_absolute_url(self):
        return reverse('blog:tag', args=[str(self.slug)])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'
        ordering = ['title']


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='URL')
    author = models.CharField(max_length=100, verbose_name='Автор')
    content = models.TextField(blank=True, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True, verbose_name='Фото')
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='posts', verbose_name='Категория')
    tags = models.ManyToManyField(Tag, blank=True, related_name='posts', verbose_name='Теги')

    def get_absolute_url(self):
        return reverse('blog:post', args=[str(self.slug)])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['-created_at']

siteblog/blog/views.py
from django.db.models import F
from django.views.generic import TemplateView, ListView, DetailView
from django.shortcuts import get_object_or_404

from .models import Post, Category, Tag


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 2
    extra_context = {
        'title': 'Classic Blog Design',
    }


class PostByCategory(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Category.objects.get(slug=self.kwargs['slug'])
        return context


class PostByTag(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Tag.objects.get(slug=self.kwargs['slug'])
        return context


class Search(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 2

    def get_queryset(self):
        return Post.objects.filter(title__icontains=self.request.GET.get('s'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Результаты поиста: ' + self.request.GET.get('s')
        context['s'] = f"s={self.request.GET.get('s')}&"
        return context


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'

    def get_object(self):
        obj = super().get_object()
        obj.views = F('views') + 1
        obj.save()
        obj.refresh_from_db()
        return obj

siteblog/blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}{{ title }} | {{ block.super }}{% endblock %}

{% block content %}
{% include 'inc/_hero.html' %}
<section class="blog-post-area">
    <div class="container">
        <div class="row">
            <div class="blog-post-area-style">
              {% for post in posts %}
              <div class="col-md-3">
                <div class="single-post">
                  {% if item.photo %}
                    <img src="{{ post.photo.url }}" class="card-img-top" alt="{{ post.title }}">
                  {% else %}
                    <img src="https://fakeimg.pl/300x200/?text=Fake%20Img&font=lobster" class="card-img-top">
                  {% endif %}
                  <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                  <h4><span>Posted By: <span class="author-name">{{ post.author }}</span></span></h4>
                  {{ post.content|safe|truncatewords:15 }}
                  <h4><time>{{ post.created_at|date:"Y-m-d H:i" }}</time></h4>
                </div>
              </div>
              {% empty %}
                Oops...
              {% endfor %}
            </div>
        </div>
    </div>
    {% include 'inc/_pagination.html' %}
</section>
{% endblock %}

siteblog/blog/templates/blog/menu_tpl.html
<div class="{{ menu_class }}">
    <ul>
        <li><a href="{% url 'blog:index' %}">Home</a></li>
        {% for item in categories %}
          <li><a href="{{ item.get_absolute_url }}">{{ item }}</a></li>
        {% endfor %}
    </ul>
</div>

siteblog/blog/templates/blog/popular_posts_tpl.html
<div class="grid">
  <h2 class="sidebar-title">Popular</h2>
  {% for popular_post in popular_posts %}
    <div class="portfolio-item popular">
    {% if item.photo %}
      <img src="{{ post.photo.url }}" class="card-img-top" alt="{{ post.title }}">
    {% else %}
      <img src="https://fakeimg.pl/300x200/?text=Fake%20Img&font=lobster" class="card-img-top">
    {% endif %}
    <div class="portfolio-text">
      <h5><a href="{{ popular_post.get_absolute_url }}">{{ popular_post.title }}</a></h5>
      <p>By {{ popular_post.author }} <span>|</span>{{ popular_post.created_at|date:"Y/m/d" }}</p>
    </div>
  </div>
  {% endfor %}
</div>

siteblog/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load sidebar %}

{% block title %}{{ post.title }} | {{ block.super }}{% endblock %}

{% block content %}

<section class="single-blog-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="border-top">
          <div class="col-md-8">
            <div class="blog-area">
              <div class="blog-area-part">
                <br><span class="h3 text-muted">Category: {{ post.category }}</span>
                <h2>{{ post.title }}</h2>
                {% if post.tags.exists %}
                  <br><br>
                  {% for tag in post.tags.all %}
                    <span class="badge bg-secondary">{{ tag }}</span>
                  {% endfor %}
                {% endif %}
                <br><br>Views: {{ post.views }}<br>
                {{ post.content|safe }}
              </div>
            </div>
          </div>
          <div class="col-md-4">
            {% show_search %}
            {% show_popular_posts %}
            {% show_tags %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

siteblog/blog/templates/blog/search_tpl.html
<div class="newsletter">
  <h2 class="sidebar-title">Search</h2>
  <form action="{% url 'blog:search' %}" method="get">
    <input type="text" name="s" placeholder="Search" class="name">
    <input type="submit" value="Search">
  </form>
</div>

siteblog/blog/templates/blog/tags_tpl.html
<div class="tags">
  <h2 class="sidebar-title">Tags</h2>
  {% for tag in tags %}
    <p><a href="{{ tag.get_absolute_url }}">{{ tag }}</a></p>
  {% endfor %}
</div>

siteblog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Dart blog{% endblock %}</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'responsive.css' %}">
</head>

<body>
    <div class="wrapper">
        {% include 'inc/_header.html' %}
        {% block content %}{% endblock %}
        {% include 'inc/_footer.html' %}
    </div>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/active.js' %}"></script>
</body>

</html>

siteblog/templates/inc/_footer.html
{% load menu %}
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="footer-bg">
                    <div class="row">
                        <div class="col-md-9">
                            {% show_menu 'footer-menu' %}
                        </div>
                        <div class="col-md-3">
                            <div class="footer-icon">
                                <p><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></p>
                            </div>
                        </div>
                    </div> .
                </div>
            </div>
        </div>
    </div>
</footer>

siteblog/templates/inc/_header.html
{% load menu %}
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="logo">
                    <h2><a href="{% url 'blog:index' %}">Classic</a></h2>
                </div>
            </div>
            <div class="col-md-10">
                {% show_menu %}
            </div>
        </div>
    </div>
</header>

siteblog/templates/inc/_hero.html
<section class="bg-text-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="bg-text">
                    <h3>Classic BLOG Design</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla </p>
                </div>
            </div>
        </div>
    </div>
</section>

siteblog/templates/inc/_pagination.html
{% if page_obj.has_other_pages %}
<div class="pegination">
  <div class="nav-links">

    {% if page_obj.has_previous %}
      <a class="page-numbers" href="?{{ s }}page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
    {% endif %}

    {% for p in page_obj.paginator.page_range %}
      {% if page_obj.number == p %}
        <span class="page-numbers current">{{ p }}</span>
      {% else %}
        <a class="page-numbers" href="?{{ s }}page={{ p }}">{{ p }}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class="page-numbers" href="?{{ s }}page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
    {% endif %}

  </div>
</div>
{% endif %}

siteblog/templates/inc/_sidebar.html
<div class="sidebar-ads">
  <img src="img/sidebar-ads.jpg" alt="">
  <p>Place For Your <br> Ad Banner</p>
</div>